function foo() {
    throw "Caught Error";
}


var coroutine = Coroutine(foo);

var caughtError = coroutine.try(); // output Caught Error
println(caughtError);
